// Distritos de Lima Metropolitana y de la Provincia Constitucional del Callao.
// Se usan en un <select> para el campo "distrito" del registro de servicios.

export const DISTRITOS = [
  {
    grupo: 'Lima',
    opciones: [
      'Ancón',
      'Ate',
      'Barranco',
      'Breña',
      'Carabayllo',
      'Chaclacayo',
      'Chorrillos',
      'Cieneguilla',
      'Comas',
      'El Agustino',
      'Independencia',
      'Jesús María',
      'La Molina',
      'La Victoria',
      'Lima (Cercado)',
      'Lince',
      'Los Olivos',
      'Lurigancho (Chosica)',
      'Lurín',
      'Magdalena del Mar',
      'Miraflores',
      'Pachacámac',
      'Pucusana',
      'Pueblo Libre',
      'Puente Piedra',
      'Punta Hermosa',
      'Punta Negra',
      'Rímac',
      'San Bartolo',
      'San Borja',
      'San Isidro',
      'San Juan de Lurigancho',
      'San Juan de Miraflores',
      'San Luis',
      'San Martín de Porres',
      'San Miguel',
      'Santa Anita',
      'Santa María del Mar',
      'Santa Rosa',
      'Santiago de Surco',
      'Surquillo',
      'Villa El Salvador',
      'Villa María del Triunfo',
    ],
  },
  {
    grupo: 'Callao',
    opciones: [
      'Bellavista',
      'Callao (Cercado)',
      'Carmen de la Legua Reynoso',
      'La Perla',
      'La Punta',
      'Mi Perú',
      'Ventanilla',
    ],
  },
]
